name: ecstatic
description: This package provides API parity with several classes of the Dart SDK but using instance properties rather than static properties.
version: 0.0.4
homepage: https://github.com/dartsidedev/ecstatic
issues: https://github.com/dartsidedev/ecstatic/issues

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
